server:
  servlet:
    context-path: /finance-solution
spring:
  h2:
    console.enabled: true
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  datasource:
    url: jdbc:h2:mem:uniqueDBNotReacheble
    username: root
    password: root
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

security:
  config:
    prefix: Bearer
    key: SECRET_KEY
    expiration: 86400

roles:
  user: >
    USER,
    MANAGER