server:
  servlet:
    context-path: /finance-solution
spring:
  main:
    allow-circular-references: true
  h2:
    console.enabled: true
    console:
      path: /h2-console
      settings.trace: true
      settings.web-allow-others: true
  datasource:
    hikari:
      maximum-pool-size: 10
      leak-detection-threshold: 2000
    url: jdbc:h2:mem:uniqueDBNotReacheble
    username: root
    password: ${PASSWORD:root}
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

security:
  config:
    prefix: Bearer
    key: ${SECRET_KEY:"Default_Secret"}
    expiration: 1

logging:
  level:
    org:
      springframework:
        security: DEBUG